
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          172239
     no. of nonzeroes in lower triangle of a =        10204833
     no. of nonzeroes in the factor l        =        57794397
     ratio of nonzeroes in factor (min/max)  =          0.7677
     number of super nodes                   =            4294
     maximum order of a front matrix         =            1407
     maximum size of a front matrix          =          990528
     maximum size of a front trapezoid       =          536598
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.6509D+10
     no. of floating point ops for solve     =      2.1916D+08
     ratio of flops for factor (min/max)     =          0.6688
     ratio of allocated memory (max/min)     =          1.2074
     number of positive pivots               =          172239
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.046875        0.039823
     time (cpu & wall) for ordering          =        0.171875        0.198880
     time (cpu & wall) for other matrix prep =        0.031250        0.047587
     time (cpu & wall) for value input       =        0.125000        0.122572
     time (cpu & wall) for matrix distrib.   =        0.531250        0.522847
     time (cpu & wall) for numeric factor    =        1.562500        1.688813
     computational rate (gflops) for factor  =       16.966062       15.697106
     time (cpu & wall) for numeric solve     =        0.046875        0.052627
     computational rate (gflops) for solve   =        4.675404        4.164378
     effective I/O rate (GB/sec) for solve   =       17.418620       15.514749

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        291890.        2. MB
                95-   1        327680.        2. MB        313101.        2. MB
                95-   2        327680.        2. MB        301630.        2. MB
                95-   3        294912.        2. MB        281252.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1245184.       10. MB       1187873.        9. MB


  Solver Memory allocated on core    0       =      228.851 MB
  Solver Memory allocated on core    1       =      236.459 MB
  Solver Memory allocated on core    2       =      230.924 MB
  Solver Memory allocated on core    3       =      195.836 MB
  Total Solver Memory allocated by all cores =      892.070 MB

